var sql_box_locked=false,only_once_elements=[],ajax_message_init=false;function suggestPassword(a){var b=a.generated_pw;b.value="";for(i=0;i<16;i++)b.value+="abcdefhjmnpqrstuvwxyz23456789ABCDEFGHJKLMNPQRSTUVWYXZ".charAt(Math.floor(Math.random()*53));a.text_pma_pw.value=b.value;a.text_pma_pw2.value=b.value;return true}
function displayPasswordGenerateButton(){$("#tr_element_before_generate_password").parent().append("<tr><td>"+PMA_messages.strGeneratePassword+'</td><td><input type="button" id="button_generate_password" value="'+PMA_messages.strGenerate+'" onclick="suggestPassword(this.form)" /><input type="text" name="generated_pw" id="generated_pw" /></td></tr>');$("#div_element_before_generate_password").parent().append('<div class="item"><label for="button_generate_password">'+PMA_messages.strGeneratePassword+
':</label><span class="options"><input type="button" id="button_generate_password" value="'+PMA_messages.strGenerate+'" onclick="suggestPassword(this.form)" /></span><input type="text" name="generated_pw" id="generated_pw" /></div>')}function selectContent(a,b,c){if(!(c&&only_once_elements[a.name])){only_once_elements[a.name]=true;b||a.select()}}
function confirmLinkDropDB(a,b){if(PMA_messages.strDoYouReally==""||typeof window.opera!="undefined")return true;var c=confirm(PMA_messages.strDropDatabaseStrongWarning+"\n"+PMA_messages.strDoYouReally+" :\n"+b);if(c)a.href+="&is_js_confirmed=1";return c}
function confirmLink(a,b){if(PMA_messages.strDoYouReally==""||typeof window.opera!="undefined")return true;var c=confirm(PMA_messages.strDoYouReally+" :\n"+b);if(c)if(typeof a.href!="undefined")a.href+="&is_js_confirmed=1";else if(typeof a.form!="undefined")a.form.action+="?is_js_confirmed=1";return c}function confirmAction(a){if(typeof window.opera!="undefined")return true;return confirm(a)}
function confirmQuery(a,b){if(PMA_messages.strDoYouReally=="")return true;else if(typeof b.value.replace=="undefined")return true;else{if(PMA_messages.strNoDropDatabases!="")if(/(^|;)\s*DROP\s+(IF EXISTS\s+)?DATABASE\s/i.test(b.value)){alert(PMA_messages.strNoDropDatabases);a.reset();b.focus();return false}var c=/^\s*ALTER\s+TABLE\s+((`[^`]+`)|([A-Za-z0-9_$]+))\s+DROP\s/i,d=/^\s*DELETE\s+FROM\s/i,e=/^\s*TRUNCATE\s/i;if(/^\s*DROP\s+(IF EXISTS\s+)?(TABLE|DATABASE|PROCEDURE)\s/i.test(b.value)||c.test(b.value)||
d.test(b.value)||e.test(b.value)){c=b.value.length>100?b.value.substr(0,100)+"\n    ...":b.value;if(confirm(PMA_messages.strDoYouReally+" :\n"+c)){a.elements.is_js_confirmed.value=1;return true}else{window.focus();b.focus();return false}}}return true}function confirmDisableRepository(){if(PMA_messages.strDoYouReally==""||typeof window.opera!="undefined")return true;return confirm(PMA_messages.strBLOBRepositoryDisableStrongWarning+"\n"+PMA_messages.strBLOBRepositoryDisableAreYouSure)}
function checkSqlQuery(a){var b=a.elements.sql_query,c=1;if(typeof b.value.replace=="undefined"){if((c=b.value==""?1:0)&&typeof a.elements.sql_file!="undefined")c=a.elements.sql_file.value==""?1:0;if(c&&typeof a.elements.sql_localfile!="undefined")c=a.elements.sql_localfile.value==""?1:0;if(c&&typeof a.elements.id_bookmark!="undefined")c=a.elements.id_bookmark.value==null||a.elements.id_bookmark.value==""}else{var d=/\s+/;if(typeof a.elements.sql_file!="undefined"&&a.elements.sql_file.value.replace(d,
"")!="")return true;if(typeof a.elements.sql_localfile!="undefined"&&a.elements.sql_localfile.value.replace(d,"")!="")return true;if(c&&typeof a.elements.id_bookmark!="undefined"&&(a.elements.id_bookmark.value!=null||a.elements.id_bookmark.value!="")&&a.elements.id_bookmark.selectedIndex!=0)return true;if(b.value.replace(d,"")!="")return confirmQuery(a,b)?true:false;a.reset();c=1}if(c){b.select();alert(PMA_messages.strFormEmpty);b.focus();return false}return true}var row_class="even";
function showDetails(a,b,c,d,e,f,h,j){var g=h.src.split("themes/");if(g[1]=="original/img/new_data_hovered.jpg"){h.src="./themes/original/img/new_data_selected_hovered.jpg";h.alt=PMA_messages.strClickToUnselect}else if(g[1]=="original/img/new_struct_hovered.jpg"){h.src="./themes/original/img/new_struct_selected_hovered.jpg";h.alt=PMA_messages.strClickToUnselect}else if(g[1]=="original/img/new_struct_selected_hovered.jpg"){h.src="./themes/original/img/new_struct_hovered.jpg";h.alt=PMA_messages.strClickToSelect}else if(g[1]==
"original/img/new_data_selected_hovered.jpg"){h.src="./themes/original/img/new_data_hovered.jpg";h.alt=PMA_messages.strClickToSelect}h=document.getElementById("list").getElementsByTagName("table")[0].getElementsByTagName("tbody")[0];row_class=row_class=="even"?"odd":"even";if(g[1]!="original/img/new_struct_selected_hovered.jpg"&&g[1]!="original/img/new_data_selected_hovered.jpg"){g=document.createElement("tr");g.setAttribute("class",row_class);g.className=row_class;g.setAttribute("id",a);a=document.createElement("td");
a.align="center";a.innerHTML=j;g.appendChild(a);a=document.createElement("td");a.align="center";j=document.createElement("td");j.align="center";var k=document.createElement("td");k.align="center";var m=document.createElement("td");m.align="center";var l=document.createElement("td");l.align="center";var n=document.createElement("td");n.align="center";var o=document.createElement("td");o.align="center";var p=document.createElement("td");p.align="center";var q=document.createElement("img");q.src="./themes/original/img/s_success.png";
if(b==""&&c==""&&d==""){a.appendChild(q);j.innerHTML="--";k.innerHTML="--";m.innerHTML="--";n.innerHTML="--";l.innerHTML="--";o.innerHTML="--";p.innerHTML="--"}else if(b==""&&d==""){a.innerHTML="--";j.innerHTML="--";k.innerHTML="--";m.innerHTML="--";l.innerHTML="--";n.innerHTML="--";o.innerHTML="--";p.innerHTML=c}else if(d==""){a.innerHTML="--";j.innerHTML="--";k.innerHTML="--";m.innerHTML="--";l.innerHTML="--";n.innerHTML="--";o.innerHTML=b;p.innerHTML=c}else{a.innerHTML="--";j.innerHTML=c;k.innerHTML=
d;m.innerHTML=b;n.innerHTML=f;l.innerHTML=e;o.innerHTML="--";p.innerHTML="--"}g.appendChild(a);g.appendChild(j);g.appendChild(k);g.appendChild(m);g.appendChild(n);g.appendChild(l);g.appendChild(o);g.appendChild(p);h.appendChild(g)}else if(g[1]!="original/img/new_struct_hovered.jpg"&&g[1]!="original/img/new_data_hovered.jpg"){b=h.getElementsByTagName("tr");for(c=c=0;c<b.length;c++)b[c].id==a&&b[c].parentNode.removeChild(b[c]);for(c=0;c<b.length;c++){row_class_element=b[c].getAttribute("class");if(row_class_element==
"even"){b[c].setAttribute("class","odd");b[c].className="odd"}else{b[c].setAttribute("class","even");b[c].className="even"}}}}
function change_Image(a){var b=a.src.split("themes/");if(b[1]=="original/img/new_data.jpg")a.src="./themes/original/img/new_data_hovered.jpg";else if(b[1]=="original/img/new_struct.jpg")a.src="./themes/original/img/new_struct_hovered.jpg";else if(b[1]=="original/img/new_struct_hovered.jpg")a.src="./themes/original/img/new_struct.jpg";else if(b[1]=="original/img/new_data_hovered.jpg")a.src="./themes/original/img/new_data.jpg";else if(b[1]=="original/img/new_data_selected.jpg")a.src="./themes/original/img/new_data_selected_hovered.jpg";
else if(b[1]=="original/img/new_struct_selected.jpg")a.src="./themes/original/img/new_struct_selected_hovered.jpg";else if(b[1]=="original/img/new_struct_selected_hovered.jpg")a.src="./themes/original/img/new_struct_selected.jpg";else if(b[1]=="original/img/new_data_selected_hovered.jpg")a.src="./themes/original/img/new_data_selected.jpg"}
function ApplySelectedChanges(a){var b=document.getElementById("list").getElementsByTagName("table")[0].getElementsByTagName("tbody")[0].getElementsByTagName("tr"),c=b.length,d,e="?token="+a+"&Table_ids=1";for(d=0;d<c;d++){e+="&";e+=d+"="+b[d].id}b=document.getElementById("delete_rows");e+=b.checked?"&checked=true":"&checked=false";location.href+=a;location.href+=e}
function validateConnection(a,b){for(var c=true,d=true,e=true,f=1;f<a.elements.length;f++)if(a.elements[f].type=="text"&&a.elements[f].name!="src_port"&&a.elements[f].name!="trg_port"){c=emptyFormElements(b,a.elements[f].name);if(c==false){element=a.elements[f].name;if(a.elements[f].name=="src_host")d=false;else if(a.elements[f].name=="trg_host")e=false;else if(a.elements[f].name=="src_socket"&&d==false||a.elements[f].name=="trg_socket"&&e==false)break}}if(!c){b.reset();element.select();alert(PMA_messages.strFormEmpty);
element.focus()}return c}function emptyCheckTheField(a,b){var c=1;c=a.elements[b];return c=typeof c.value.replace!="undefined"?c.value.replace(/\s+/,"")==""?1:0:c.value==""?1:0}function emptyFormElements(a,b){return emptyCheckTheField(a,b)}
function checkFormElementInRange(a,b,c,d,e){a=a.elements[b];b=parseInt(a.value);if(typeof d=="undefined")d=0;if(typeof e=="undefined")e=Number.MAX_VALUE;if(isNaN(b)){a.select();alert(PMA_messages.strNotNumber);a.focus();return false}else if(b<d||b>e){a.select();alert(c.replace("%d",b));a.focus();return false}else a.value=b;return true}
function checkTableEditForm(a,b){var c=0,d,e,f,h;for(d=0;d<b;d++){e="#field_"+d+"_2";e=$(e);h=e.val();if(h=="VARCHAR"||h=="CHAR"||h=="BIT"||h=="VARBINARY"||h=="BINARY"){e=$("#field_"+d+"_3");h=parseInt(e.val());f=$("#field_"+d+"_1");if(isNaN(h)&&f.val()!=""){e.select();alert(PMA_messages.strNotNumber);e.focus();return false}}if(c==0){e="field_"+d+"_1";emptyCheckTheField(a,e)||(c=1)}}if(c==0){c=a.elements.field_0_1;alert(PMA_messages.strFormEmpty);c.focus();return false}return true}
function checkTransmitDump(a,b){var c=a.elements;if(b=="zip"&&c.zip.checked){if(!c.asfile.checked)a.elements.asfile.checked=true;if(typeof c.gzip!="undefined"&&c.gzip.checked)a.elements.gzip.checked=false;if(typeof c.bzip!="undefined"&&c.bzip.checked)a.elements.bzip.checked=false}else if(b=="gzip"&&c.gzip.checked){if(!c.asfile.checked)a.elements.asfile.checked=true;if(typeof c.zip!="undefined"&&c.zip.checked)a.elements.zip.checked=false;if(typeof c.bzip!="undefined"&&c.bzip.checked)a.elements.bzip.checked=
false}else if(b=="bzip"&&c.bzip.checked){if(!c.asfile.checked)a.elements.asfile.checked=true;if(typeof c.zip!="undefined"&&c.zip.checked)a.elements.zip.checked=false;if(typeof c.gzip!="undefined"&&c.gzip.checked)a.elements.gzip.checked=false}else if(b=="transmit"&&!c.asfile.checked){if(typeof c.zip!="undefined"&&c.zip.checked)a.elements.zip.checked=false;if(typeof c.gzip!="undefined"&&c.gzip.checked)a.elements.gzip.checked=false;if(typeof c.bzip!="undefined"&&c.bzip.checked)a.elements.bzip.checked=
false}return true}$(document).ready(function(){$("tr.odd:not(.noclick), tr.even:not(.noclick)").live("click",function(){var a=$(this);a.toggleClass("marked");a.children().toggleClass("marked")})});$(document).ready(function(){$("tr.odd, tr.even").live("hover",function(){var a=$(this);a.toggleClass("hover");a.children().toggleClass("hover")})});var marked_row=[];function markAllRows(a){$("#"+a).find("input:checkbox:enabled").attr("checked","checked").parents("tr").addClass("marked");return true}
function unMarkAllRows(a){$("#"+a).find("input:checkbox:enabled").removeAttr("checked").parents("tr").removeClass("marked");return true}function setCheckboxes(a,b){b?$("#"+a).find("input:checkbox").attr("checked","checked"):$("#"+a).find("input:checkbox").removeAttr("checked");return true}
function setSelectOptions(a,b,c){c?$("form[name='"+a+"']").find("select[name='"+b+"']").find("option").attr("selected","selected"):$("form[name='"+a+"']").find("select[name="+b+"]").find("option").removeAttr("selected");return true}
function insertQuery(a){var b=document.sqlform.dummy,c="",d=document.sqlform.table.value;if(b.options.length>0){sql_box_locked=true;for(var e="",f="",h="",j=0,g=0;g<b.options.length;g++){j++;if(j>1){e+=", ";f+=",";h+=","}e+=b.options[g].value;f+="[value-"+j+"]";h+=b.options[g].value+"=[value-"+j+"]"}if(a=="selectall")c="SELECT * FROM `"+d+"` WHERE 1";else if(a=="select")c="SELECT "+e+" FROM `"+d+"` WHERE 1";else if(a=="insert")c="INSERT INTO `"+d+"`("+e+") VALUES ("+f+")";else if(a=="update")c="UPDATE `"+
d+"` SET "+h+" WHERE 1";else if(a=="delete")c="DELETE FROM `"+d+"` WHERE 1";document.sqlform.sql_query.value=c;sql_box_locked=false}}
function insertValueQuery(){var a=document.sqlform.sql_query,b=document.sqlform.dummy;if(b.options.length>0){sql_box_locked=true;for(var c="",d=0,e=0;e<b.options.length;e++)if(b.options[e].selected){d++;if(d>1)c+=", ";c+=b.options[e].value}if(document.selection){a.focus();sel=document.selection.createRange();sel.text=c;document.sqlform.insert.focus()}else if(document.sqlform.sql_query.selectionStart||document.sqlform.sql_query.selectionStart=="0"){b=document.sqlform.sql_query.selectionEnd;d=document.sqlform.sql_query.value;
a.value=d.substring(0,document.sqlform.sql_query.selectionStart)+c+d.substring(b,d.length)}else a.value+=c;sql_box_locked=false}}function goToUrl(a,b){eval("document.location.href = '"+b+"pos="+a.options[a.selectedIndex].value+"'")}function getElement(a,b){if(document.layers){b=b?b:self;if(b.document.layers[a])return b.document.layers[a];for(W=0;W<b.document.layers.length;)return getElement(a,b.document.layers[W])}if(document.all)return document.all[a];return document.getElementById(a)}
function refreshDragOption(a){if($("#"+a).css("visibility")=="visible"){refreshLayout();TableDragInit()}}function refreshLayout(){var a=$("#pdflayout"),b=$("#orientation_opt").val(),c=$("#paper_opt").length==1?$("#paper_opt").val():"A4";if(b=="P"){posa="x";posb="y"}else{posa="y";posb="x"}a.css("width",pdfPaperSize(c,posa)+"px");a.css("height",pdfPaperSize(c,posb)+"px")}
function ToggleDragDrop(a){a=$("#"+a);if(a.css("visibility")=="hidden"){PDFinit();a.css("visibility","visible");a.css("display","block");$("#showwysiwyg").val("1")}else{a.css("visibility","hidden");a.css("display","none");$("#showwysiwyg").val("0")}}function dragPlace(a,b,c){a=$("#table_"+a);b=="x"?a.css("left",c+"px"):a.css("top",c+"px")}
function pdfPaperSize(a,b){switch(a.toUpperCase()){case "4A0":return b=="x"?4767.87:6740.79;case "2A0":return b=="x"?3370.39:4767.87;case "A0":return b=="x"?2383.94:3370.39;case "A1":return b=="x"?1683.78:2383.94;case "A2":return b=="x"?1190.55:1683.78;case "A3":return b=="x"?841.89:1190.55;case "A4":return b=="x"?595.28:841.89;case "A5":return b=="x"?419.53:595.28;case "A6":return b=="x"?297.64:419.53;case "A7":return b=="x"?209.76:297.64;case "A8":return b=="x"?147.4:209.76;case "A9":return b==
"x"?104.88:147.4;case "A10":return b=="x"?73.7:104.88;case "B0":return b=="x"?2834.65:4008.19;case "B1":return b=="x"?2004.09:2834.65;case "B2":return b=="x"?1417.32:2004.09;case "B3":return b=="x"?1000.63:1417.32;case "B4":return b=="x"?708.66:1000.63;case "B5":return b=="x"?498.9:708.66;case "B6":return b=="x"?354.33:498.9;case "B7":return b=="x"?249.45:354.33;case "B8":return b=="x"?175.75:249.45;case "B9":return b=="x"?124.72:175.75;case "B10":return b=="x"?87.87:124.72;case "C0":return b=="x"?
2599.37:3676.54;case "C1":return b=="x"?1836.85:2599.37;case "C2":return b=="x"?1298.27:1836.85;case "C3":return b=="x"?918.43:1298.27;case "C4":return b=="x"?649.13:918.43;case "C5":return b=="x"?459.21:649.13;case "C6":return b=="x"?323.15:459.21;case "C7":return b=="x"?229.61:323.15;case "C8":return b=="x"?161.57:229.61;case "C9":return b=="x"?113.39:161.57;case "C10":return b=="x"?79.37:113.39;case "RA0":return b=="x"?2437.8:3458.27;case "RA1":return b=="x"?1729.13:2437.8;case "RA2":return b==
"x"?1218.9:1729.13;case "RA3":return b=="x"?864.57:1218.9;case "RA4":return b=="x"?609.45:864.57;case "SRA0":return b=="x"?2551.18:3628.35;case "SRA1":return b=="x"?1814.17:2551.18;case "SRA2":return b=="x"?1275.59:1814.17;case "SRA3":return b=="x"?907.09:1275.59;case "SRA4":return b=="x"?637.8:907.09;case "LETTER":return b=="x"?612:792;case "LEGAL":return b=="x"?612:1008;case "EXECUTIVE":return b=="x"?521.86:756;case "FOLIO":return b=="x"?612:936}return 0}
function popupBSMedia(a,b,c,d,e,f){if(e==undefined)e=640;if(f==undefined)f=480;window.open("bs_play_media.php?"+a+"&bs_reference="+b+"&media_type="+c+"&custom_type="+d,"viewBSMedia","width="+e+", height="+f+", resizable=1, scrollbars=1, status=0")}function requestMIMETypeChange(a,b,c,d){if(undefined==d)d="";var e=prompt("Enter custom MIME type",d);e&&e!=d&&changeMIMEType(a,b,c,e)}
function changeMIMEType(a,b,c,d){jQuery.post("bs_change_mime_type.php",{bs_db:a,bs_table:b,bs_reference:c,bs_new_mime_type:d})}
$(document).ready(function(){var a,b,c,d,e;a=$(".inner_sql").html();$("#inline_edit").click(function(){b=$("input[name='db']").val();c=$("input[name='table']").val();d=$("input[name='token']").val();e=$("input[name='sql_query']").val();$(".inner_sql").replaceWith('<textarea name="sql_query_edit" id="sql_query_edit">'+e+'</textarea><input type="button" id="btnSave" value="'+PMA_messages.strGo+'"><input type="button" id="btnDiscard" value="'+PMA_messages.strCancel+'">');return false});$("#btnSave").live("click",
function(){window.location.replace("import.php?db="+b+"&table="+c+"&sql_query="+$("#sql_query_edit").val()+"&show_query=1&token="+d+"")});$("#btnDiscard").live("click",function(){$(".sql").html('<span class="syntax"><span class="inner_sql">'+a+"</span></span>")});$(".sqlbutton").click(function(f){insertQuery(f.target.id);return false});$("#export_type").change(function(){if($("#export_type").val()=="svg"){$("#show_grid_opt").attr("disabled","disabled");$("#orientation_opt").attr("disabled","disabled");
$("#with_doc").attr("disabled","disabled");$("#show_table_dim_opt").removeAttr("disabled");$("#all_table_same_wide").removeAttr("disabled");$("#paper_opt").removeAttr("disabled","disabled");$("#show_color_opt").removeAttr("disabled","disabled")}else if($("#export_type").val()=="dia"){$("#show_grid_opt").attr("disabled","disabled");$("#with_doc").attr("disabled","disabled");$("#show_table_dim_opt").attr("disabled","disabled");$("#all_table_same_wide").attr("disabled","disabled");$("#paper_opt").removeAttr("disabled",
"disabled");$("#show_color_opt").removeAttr("disabled","disabled");$("#orientation_opt").removeAttr("disabled","disabled")}else if($("#export_type").val()=="eps"){$("#show_grid_opt").attr("disabled","disabled");$("#orientation_opt").removeAttr("disabled");$("#with_doc").attr("disabled","disabled");$("#show_table_dim_opt").attr("disabled","disabled");$("#all_table_same_wide").attr("disabled","disabled");$("#paper_opt").attr("disabled","disabled");$("#show_color_opt").attr("disabled","disabled")}else if($("#export_type").val()==
"pdf"){$("#show_grid_opt").removeAttr("disabled");$("#orientation_opt").removeAttr("disabled");$("#with_doc").removeAttr("disabled","disabled");$("#show_table_dim_opt").removeAttr("disabled","disabled");$("#all_table_same_wide").removeAttr("disabled","disabled");$("#paper_opt").removeAttr("disabled","disabled");$("#show_color_opt").removeAttr("disabled","disabled")}});$("#sqlquery").focus();if($("#input_username"))$("#input_username").val()==""?$("#input_username").focus():$("#input_password").focus()});
function PMA_ajaxInsertResponse(a){$.each(a,function(b,c){var d="#"+b,e=$("#"+c).html();$(d).html(e)})}
function PMA_ajaxShowMessage(a,b){if(a=="")return true;var c=a?a:PMA_messages.strLoading,d=b?b:5E3;if(ajax_message_init)$("#loading").clearQueue().html(c).slideDown("medium").delay(d).slideUp("medium",function(){$(this).html("").hide()});else{$(function(){$('<div id="loading_parent"></div>').insertBefore("#serverinfo");$('<span id="loading" class="ajax_notification"></span>').appendTo("#loading_parent").html(c).slideDown("medium").delay(d).slideUp("medium",function(){$(this).html("").hide()})},"top.frame_content");
ajax_message_init=true}}function toggle_enum_notice(a){var b=a.attr("id").split("_")[1];b+="_"+(parseInt(a.attr("id").split("_")[2])+1);a=a.attr("value");a=="ENUM"||a=="SET"?$("p[id='enum_notice_"+b+"']").show():$("p[id='enum_notice_"+b+"']").hide()}
jQuery.fn.PMA_confirm=function(a,b,c){if(PMA_messages.strDoYouReally=="")return true;var d={};d[PMA_messages.strOK]=function(){$(this).dialog("close").remove();$.isFunction(c)&&c.call(this,b)};d[PMA_messages.strCancel]=function(){$(this).dialog("close").remove()};$('<div id="confirm_dialog"></div>').prepend(a).dialog({buttons:d})};
jQuery.fn.PMA_sort_table=function(a){return this.each(function(){var b=$(this),c=$(this).find("tr").get();$.each(c,function(d,e){e.sortKey=$.trim($(e).find(a).text().toLowerCase())});c.sort(function(d,e){if(d.sortKey<e.sortKey)return-1;if(d.sortKey>e.sortKey)return 1;return 0});$.each(c,function(d,e){$(b).append(e);e.sortKey=null});$(this).find("tr:odd").removeClass("even").addClass("odd").end().find("tr:even").removeClass("odd").addClass("even")})};
$(document).ready(function(){$("#create_table_form_minimal").live("submit",function(a){a.preventDefault();$form=$(this);var b={};b[PMA_messages.strCancel]=function(){$(this).dialog("close").remove()};PMA_ajaxShowMessage();$form.find("input:hidden").is("#ajax_request_hidden")||$form.append('<input type="hidden" id="ajax_request_hidden" name="ajax_request" value="true" />');$.get($form.attr("action"),$form.serialize(),function(c){$('<div id="create_table_dialog"></div>').append(c).dialog({title:PMA_messages.strCreateTable,
width:900,buttons:b})});$form.find("input[name=table],input[name=num_fields]").val("")});$("#create_table_form input[name=do_save_data]").live("click",function(a){a.preventDefault();a=$("#create_table_form");PMA_ajaxShowMessage(PMA_messages.strProcessingRequest);a.find("input:hidden").is("#ajax_request_hidden")||a.append('<input type="hidden" id="ajax_request_hidden" name="ajax_request" value="true" />');$.post(a.attr("action"),a.serialize()+"&do_save_data="+$(this).val(),function(b){if(b.success==
true){PMA_ajaxShowMessage(b.message);$("#create_table_dialog").dialog("close").remove();var c=$("#tablesForm").find("tbody").not("#tbl_summary_row");if(c.length==0)window.parent&&window.parent.frame_content&&window.parent.frame_content.location.reload();else{var d=$(c).find("tr:last");d=$(d).find("input:checkbox").attr("id").match(/\d+/)[0];d="checkbox_tbl_"+(parseFloat(d)+1);$(b.new_table_string).find("input:checkbox").val(d).end().appendTo(c);$(c).PMA_sort_table("th")}window.parent&&window.parent.frame_navigation&&
window.parent.frame_navigation.location.reload()}else PMA_ajaxShowMessage(b.error)})});$("#create_table_form input[name=submit_num_fields]").live("click",function(a){a.preventDefault();a=$("#create_table_form");PMA_ajaxShowMessage(PMA_messages.strProcessingRequest);a.find("input:hidden").is("#ajax_request_hidden")||a.append('<input type="hidden" id="ajax_request_hidden" name="ajax_request" value="true" />');$.post(a.attr("action"),a.serialize()+"&submit_num_fields="+$(this).val(),function(b){$("#create_table_dialog").html(b)})})},
"top.frame_content");
$(document).ready(function(){$("#empty_table_anchor").live("click",function(a){a.preventDefault();a="TRUNCATE TABLE "+window.parent.table;$(this).PMA_confirm(a,$(this).attr("href"),function(b){PMA_ajaxShowMessage(PMA_messages.strProcessingRequest);$.get(b,{is_js_confirmed:1,ajax_request:true},function(c){if(c.success==true){PMA_ajaxShowMessage(c.message);$("#topmenucontainer").next("div").remove().end().after(c.sql_query)}else PMA_ajaxShowMessage(c.error)})})});$("#drop_table_anchor").live("click",function(a){a.preventDefault();
a="DROP TABLE/VIEW "+window.parent.table;$(this).PMA_confirm(a,$(this).attr("href"),function(b){PMA_ajaxShowMessage(PMA_messages.strProcessingRequest);$.get(b,{is_js_confirmed:1,ajax_request:true},function(c){if(c.success==true){PMA_ajaxShowMessage(c.message);$("#topmenucontainer").next("div").remove().end().after(c.sql_query);window.parent.table="";window.parent&&window.parent.frame_navigation&&window.parent.frame_navigation.location.reload()}else PMA_ajaxShowMessage(c.error)})})})},"top.frame_content");
$(document).ready(function(){$(".drop_trigger_anchor").live("click",function(a){a.preventDefault();var b=$(this).parents("tr");a="DROP TRIGGER IF EXISTS `"+$(b).children("td:first").text()+"`";$(this).PMA_confirm(a,$(this).attr("href"),function(c){PMA_ajaxShowMessage(PMA_messages.strProcessingRequest);$.get(c,{is_js_confirmed:1,ajax_request:true},function(d){if(d.success==true){PMA_ajaxShowMessage(d.message);$("#topmenucontainer").next("div").remove().end().after(d.sql_query);$(b).hide("medium").remove()}else PMA_ajaxShowMessage(d.error)})})})},
"top.frame_content");$(document).ready(function(){$("#drop_db_anchor").live("click",function(a){a.preventDefault();a=PMA_messages.strDropDatabaseStrongWarning+"\n"+PMA_messages.strDoYouReally+" :\nDROP DATABASE "+window.parent.db;$(this).PMA_confirm(a,$(this).attr("href"),function(b){PMA_ajaxShowMessage(PMA_messages.strProcessingRequest);$.get(b,{is_js_confirmed:"1",ajax_request:true},function(){window.parent.refreshNavigation();window.parent.refreshMain()})})})});
$(document).ready(function(){$("#create_database_form").live("submit",function(a){a.preventDefault();$form=$(this);PMA_ajaxShowMessage(PMA_messages.strProcessingRequest);$form.find("input:hidden").is("#ajax_request_hidden")||$form.append('<input type="hidden" id="ajax_request_hidden" name="ajax_request" value="true" />');$.post($form.attr("action"),$form.serialize(),function(b){if(b.success==true){PMA_ajaxShowMessage(b.message);$("#tabledatabases").find("tbody").append(b.new_db_string).PMA_sort_table(".name").find("#db_summary_row").appendTo("#tabledatabases tbody").removeClass("odd even");
b=$("#databases_count");var c=parseInt(b.text());b.text(++c);window.parent&&window.parent.frame_navigation&&window.parent.frame_navigation.location.reload()}else PMA_ajaxShowMessage(b.error)})})});
$(document).ready(function(){$("#change_password_anchor").live("click",function(a){a.preventDefault();var b={};b[PMA_messages.strCancel]=function(){$(this).dialog("close").remove()};$.get($(this).attr("href"),{ajax_request:true},function(c){$('<div id="change_password_dialog></div>').dialog({title:PMA_messages.strChangePassword,width:600,buttons:b}).append(c);displayPasswordGenerateButton()})});$("#change_password_form").find("input[name=change_pw]").live("click",function(a){a.preventDefault();a=
$("#change_password_form");var b=$(this).val();PMA_ajaxShowMessage(PMA_messages.strProcessingRequest);$(a).append('<input type="hidden" name="ajax_request" value="true" />');$.post($(a).attr("action"),$(a).serialize()+"&change_pw="+b,function(c){if(c.success==true){PMA_ajaxShowMessage(c.message);$("#topmenucontainer").after(c.sql_query);$("#change_password_dialog").hide().remove();$("#edit_user_dialog").dialog("close").remove()}else PMA_ajaxShowMessage(c.error)})})});
$(document).ready(function(){$.each($("select[class='column_type']"),function(){toggle_enum_notice($(this))});$("select[class='column_type']").change(function(){toggle_enum_notice($(this))})});function disable_popup(){$("#popup_background").fadeOut("fast");$("#enum_editor").fadeOut("fast");$("#enum_editor #values input").remove();$("#enum_editor input[type='hidden']").remove()}
$(document).ready(function(){$("a[class='open_enum_editor']").click(function(){var a=document.documentElement.clientWidth,b=document.documentElement.clientHeight,c=a/2,d=b*0.8;b=b/2-d/2;a=a/2-c/2;$("#enum_editor").css({position:"absolute",top:b,left:a,width:c,height:d});$("#popup_background").css({opacity:"0.7"});$("#popup_background").fadeIn("fast");$("#enum_editor").fadeIn("fast");c=$(this).parent().prev("input").attr("value").split(",");$.each(c,function(e,f){if(jQuery.trim(f)!=""){if(f.substr(0,
1)!="'")f="'"+f;if(f.substr(f.length-1,f.length)!="'")f+="'";f=f.substr(1,f.length-2).replace(/''/g,"'").replace(/\\\\/g,"\\").replace(/\\'/g,"'").replace(/'/g,"&#039;");f=f.replace(/>/g,"&gt;");$("#enum_editor #values").append("<input type='text' value="+f+" />")}});$("#enum_editor").append("<input type='hidden' value='"+$(this).parent().prev("input").attr("id")+"' />");return false});$("a[class='close_enum_editor']").click(function(){disable_popup()});$("a[class='cancel_enum_editor']").click(function(){disable_popup()});
$("a[class='add_value']").click(function(){$("#enum_editor #values").append("<input type='text' />")});$("#enum_editor input[type='submit']").click(function(){var a=[];$.each($("#enum_editor #values input"),function(c,d){val=jQuery.trim(d.value);val!=""&&a.push("'"+val.replace(/\\/g,"\\\\").replace(/'/g,"''")+"'")});var b=$("#enum_editor input[type='hidden']").attr("value");$("input[id='"+b+"']").attr("value",a.join(","));disable_popup()});if($("input[type='hidden'][name='table_type']").attr("value")==
"table"){$("table[id='tablestructure'] td[class='browse']").remove();$("table[id='tablestructure'] td[class='primary']").remove();$("table[id='tablestructure'] td[class='unique']").remove();$("table[id='tablestructure'] td[class='index']").remove();$("table[id='tablestructure'] td[class='fulltext']").remove();$("table[id='tablestructure'] th[class='action']").attr("colspan",3);$("table[id='tablestructure'] td[class='more_opts']").show();$.each($(".structure_actions_dropdown"),function(){var a=$(this).parent().offset().left+
$(this).parent().innerWidth()-$(this).innerWidth(),b=$(this).parent().offset().top+$(this).parent().innerHeight();$(this).offset({top:b,left:a})});$("iframe[class='IE_hack']").width($("select[name='after_field']").width());$("iframe[class='IE_hack']").height($("select[name='after_field']").height());$("iframe[class='IE_hack']").offset({top:$("select[name='after_field']").offset().top,left:$("select[name='after_field']").offset().left});$("table[id='tablestructure'] td[class='more_opts']").mouseenter(function(){if($.browser.msie&&
$.browser.version=="6.0"){$("iframe[class='IE_hack']").show();$("iframe[class='IE_hack']").width($("select[name='after_field']").width()+4);$("iframe[class='IE_hack']").height($("select[name='after_field']").height()+4);$("iframe[class='IE_hack']").offset({top:$("select[name='after_field']").offset().top,left:$("select[name='after_field']").offset().left})}$(".structure_actions_dropdown").hide();$(this).children(".structure_actions_dropdown").show();if($.browser.msie){var a=$(this).offset().left+
$(this).innerWidth()-$(this).children(".structure_actions_dropdown").innerWidth(),b=$(this).offset().top+$(this).innerHeight();$(this).children(".structure_actions_dropdown").offset({top:b,left:a})}});$(".structure_actions_dropdown").mouseleave(function(){$(this).hide();$.browser.msie&&$.browser.version=="6.0"&&$("iframe[class='IE_hack']").hide()})}});
$(document).ready(function(){$(".footnotes").hide();$(".footnotes span").each(function(){$(this).children("sup").remove()});$(".footnotes").css("border","none");$(".footnotes").css("padding","0px");$("sup[class='footnotemarker']").hide();$("img[class='footnotemarker']").show();$("img[class='footnotemarker']").each(function(){var a=$(this).attr("id");a=a.split("_")[1];a=$(".footnotes span[id='footnote_"+a+"']").html();$(this).qtip({content:a,show:{delay:0},hide:{when:"unfocus",delay:0},style:{background:"#ffffcc"}})})});
function menuResize(){var a=$("#topmenu"),b=a.width()-5,c=a.find(".submenu"),d=c.outerWidth(true),e=c.find("ul");a=a.find("> li");for(var f=e.find("li"),h=f.length>0,j=h?d:0,g=0,k=0;k<a.length-1;k++){var m=$(a[k]),l=m.outerWidth(true);m.data("width",l);j+=l;if(j>b){j-=l;if(j+d<b)g=k;else{g=k-1;j-=$(a[k-1]).data("width")}break}}if(g>0){for(k=g;k<a.length-1;k++)$(a[k])[h?"prependTo":"appendTo"](e);c.show()}else if(h){j-=d;for(k=0;k<f.length;k++){j+=$(f[k]).data("width");if(j+d<b||k==f.length-1&&j<b){$(f[k]).insertBefore(c);
k==f.length-1&&c.hide()}else break}}c.find(".tabactive").length?c.addClass("active").find("> a").removeClass("tab").addClass("tabactive"):c.removeClass("active").find("> a").addClass("tab").removeClass("tabactive")}
$(function(){var a=$("#topmenu");if(a.length!=0){var b=$("<a />",{href:"#","class":"tab"}).text(PMA_messages.strMore).click(function(d){d.preventDefault()}),c=a.find("li:first-child img");c.length&&c.clone().attr("src",c.attr("src").replace(/\/[^\/]+$/,"/b_more.png")).prependTo(b);b=$("<li />",{"class":"submenu"}).append(b).append($("<ul />")).mouseenter(function(){$(this).find("ul .tabactive").length==0&&$(this).addClass("submenuhover").find("> a").addClass("tabactive")}).mouseleave(function(){$(this).find("ul .tabactive").length==
0&&$(this).removeClass("submenuhover").find("> a").removeClass("tabactive")}).hide();a.append(b);$(window).resize(menuResize);menuResize()}});
$(document).ready(function(){$(".multi_checkbox").live("click",function(a){var b=this.id,c=b.replace("_right","_left"),d=b.replace("_left","_right"),e="";e=b==c?d:c;var f=$("#"+b);b=$("#"+e);if(a.shiftKey){var h=$(".multi_checkbox").index(f);a=$(".multi_checkbox").filter(".last_clicked");var j=$(".multi_checkbox").index(a);$(".multi_checkbox").filter(function(g){return h>j&&g>j&&g<h||j>h&&g<j&&g>h}).each(function(){var g=$(this);f.is(":checked")?g.attr("checked",true):g.attr("checked",false)})}$(".multi_checkbox").removeClass("last_clicked");
f.addClass("last_clicked");f.is(":checked")?b.attr("checked",true):b.attr("checked",false)})});function PMA_getRowNumber(a){return parseInt(a.split(/row_/)[1])}$(document).ready(function(){$(".vpointer").live("hover",function(){var a=$(this);a=PMA_getRowNumber(a.attr("class"));$(".vpointer").filter(".row_"+a).toggleClass("hover")})});
$(document).ready(function(){$(".vmarker").live("click",function(){var a=$(this);a=PMA_getRowNumber(a.attr("class"));$(".vmarker").filter(".row_"+a).toggleClass("marked")});$("#visual_builder_anchor").show()});
