function PMA_urldecode(c){return decodeURIComponent(c.replace(/\+/g,"%20"))}function getFieldName(c,a){if(a=="vertical")var b=c.siblings("th").find("a").text();else{b=c.index();b=window.parent.text_dir=="ltr"?c.parents("table").find("thead").find("th:nth("+(b-3)+") a").text():c.parents("table").find("thead").find("th:nth("+b+") a").text()}return b=$.trim(b)}
function appendInlineAnchor(c){if(c=="vertical"){$("#table_results tr").find(".edit_row_anchor").removeClass(".edit_row_anchor").parent().each(function(){var a=$(this),b=a.clone(),g=b.find("img:first").attr("title",PMA_messages.strInlineEdit);b.find("td").addClass("inline_edit_anchor").find("a").attr("href","#").find("span").text(PMA_messages.strInlineEdit).prepend(g);b.insertAfter(a)});$("#table_results").find("tr").find(":checkbox").closest("tr").find("th").attr("rowspan","4")}else{$(".edit_row_anchor").each(function(){$this_td=
$(this);$this_td.removeClass("edit_row_anchor");var a=$this_td.clone(),b=a.find("img").attr("title",PMA_messages.strInlineEdit);a.addClass("inline_edit_anchor").find("a").attr("href","#").find("span").text(PMA_messages.strInlineEdit).prepend(b);$this_td.after(a)});$("#rowsDeleteForm").find("thead").find("th").each(function(){$(this).attr("colspan")==3&&$(this).attr("colspan","4")})}}
$(document).ready(function(){$.ajaxSetup({cache:"false"});var c=$("#top_direction_dropdown").val();$("#top_direction_dropdown, #bottom_direction_dropdown").live("change",function(){c=$(this).val()});$("#sqlqueryresults").live("appendAnchor",function(){appendInlineAnchor(c)});$("#sqlqueryresults").trigger("appendAnchor");if(!$("#sqlqueryform").find("a").is("#togglequerybox")){$('<a id="togglequerybox"></a>').html(PMA_messages.strHideQueryBox).appendTo("#sqlqueryform");$("#togglequerybox").bind("click",
function(){var a=$(this);a.siblings().slideToggle("medium");a.text()==PMA_messages.strHideQueryBox?a.text(PMA_messages.strShowQueryBox):a.text(PMA_messages.strHideQueryBox);return false})}$("#sqlqueryform").live("submit",function(a){a.preventDefault();$(".error").remove();$form=$(this);PMA_ajaxShowMessage();$form.find("input:hidden").is("#ajax_request_hidden")||$form.append('<input type="hidden" id="ajax_request_hidden" name="ajax_request" value="true" />');$.post($(this).attr("action"),$(this).serialize(),
function(b){if(b.success==true){PMA_ajaxShowMessage(b.message);$("#sqlqueryresults").show();if(typeof b.reload!="undefined"){$form.find("input[name=db]").val(b.db);$form.find("input[name=ajax_request]").remove();$form.append('<input type="hidden" name="reload" value="true" />');$.post("db_sql.php",$form.serialize(),function(g){$("body").html(g)})}}else if(b.success==false){$("#sqlqueryform").before(b.error);$("#sqlqueryresults").hide()}else{$("#sqlqueryresults").show();$("#sqlqueryresults").html(b);
$("#sqlqueryresults").trigger("appendAnchor");$("#togglequerybox").siblings(":visible").length>0&&$("#togglequerybox").trigger("click")}})});$("input[name=navig]").live("click",function(a){a.preventDefault();PMA_ajaxShowMessage();a=$(this).parent("form");$(a).append('<input type="hidden" name="ajax_request" value="true" />');$.post($(a).attr("action"),$(a).serialize(),function(b){$("#sqlqueryresults").html(b);$("#sqlqueryresults").trigger("appendAnchor")})});$("#pageselector").live("change",function(a){a.preventDefault();
PMA_ajaxShowMessage();$.get($(this).attr("href"),$(this).serialize()+"&ajax_request=true",function(b){$("#sqlqueryresults").html(b);$("#sqlqueryresults").trigger("appendAnchor")})});$("#table_results").find("a[title=Sort]").live("click",function(a){a.preventDefault();PMA_ajaxShowMessage();$.get($(this).attr("href"),$(this).serialize()+"&ajax_request=true",function(b){$("#sqlqueryresults").html(b);$("#sqlqueryresults").trigger("appendAnchor")})});$("#displayOptionsForm").live("submit",function(a){a.preventDefault();
$.post($(this).attr("action"),$(this).serialize()+"&ajax_request=true",function(b){$("#sqlqueryresults").html(b);$("#sqlqueryresults").trigger("appendAnchor")})});$(".inline_edit_anchor").live("click",function(a){a.preventDefault();$(this).removeClass("inline_edit_anchor").addClass("inline_edit_active");if(c=="vertical"){a=$(this).index();var b=$(this).parents("tbody").find("tr").find(".data_inline_edit:nth("+a+")"),g=$(this).parents("tbody").find("tr").find(".where_clause:nth("+a+")").val()}else{b=
$(this).parent("tr").find(".data_inline_edit");g=$(this).parent("tr").find(".where_clause").val()}b.each(function(){var k=$(this).html(),d=$(this),h=getFieldName(d,c);if(d.is(":not(.truncated, .transformed, .relation, .enum, .null)")){d.html("<textarea>"+k+"</textarea>").append('<span class="original_data">'+k+"</span>");$(".original_data").hide()}else if(d.is(".truncated, .transformed"))$.post("sql.php",{token:window.parent.token,db:window.parent.db,ajax_request:true,sql_query:"SELECT "+h+" FROM "+
window.parent.table+" WHERE "+g,inline_edit:true},function(i){if(i.success==true){d.html("<textarea>"+i.value+"</textarea>").append('<span class="original_data">'+k+"</span>");$(".original_data").hide()}else PMA_ajaxShowMessage(i.error)});else if(d.is(".relation")){var l=d.find("a").text();h={ajax_request:true,get_relational_values:true,db:window.parent.db,table:window.parent.table,column:h,token:window.parent.token,curr_value:l};$.post("sql.php",h,function(i){d.html(i.dropdown).append('<span class="original_data">'+
k+"</span>");$(".original_data").hide()})}else if(d.is(".enum")){l=d.text();h={ajax_request:true,get_enum_values:true,db:window.parent.db,table:window.parent.table,column:h,token:window.parent.token,curr_value:l};$.post("sql.php",h,function(i){d.html(i.dropdown).append('<span class="original_data">'+k+"</span>");$(".original_data").hide()})}else if(d.is(".null")){d.html("<textarea></textarea>").append('<span class="original_data">NULL</span>');$(".original_data").hide()}})});$(".inline_edit_active").live("click",
function(a){a.preventDefault();var b=$(this);if(c=="vertical"){a=b.index();var g=b.parents("tbody").find("tr").find(".data_inline_edit:nth("+a+")");a=b.parents("tbody").find("tr").find(".where_clause:nth("+a+")").val()}else{g=b.parent("tr").find(".data_inline_edit");a=b.parent("tr").find(".where_clause").val()}var k=b.is(".nonunique")?0:1,d={},h={},l={},i=false;g.each(function(){var e=$(this),f=getFieldName(e,c),j={};if(e.is(".transformed"))i=true;if(e.is(":not(.relation, .enum)")){j[f]=e.find("textarea").val();
e.is(".transformed")&&$.extend(l,j)}else{j[f]=e.find("select").val();e.is(".relation")&&$.extend(h,j)}$.extend(d,j)});var m="UPDATE "+window.parent.table+" SET ";$.each(d,function(e,f){if(f.length==0)f="NULL";m+=" "+e+"='"+f+"' , "});m=m.replace(/,\s$/,"");m+=" WHERE "+PMA_urldecode(a);var r=$.param(h),s=$.param(l);$.post("tbl_replace.php",{ajax_request:true,sql_query:m,disp_direction:c,token:window.parent.token,db:window.parent.db,table:window.parent.table,clause_is_unique:k,where_clause:a,rel_fields_list:r,
do_transformations:i,transform_fields_list:s,"goto":"sql.php",submit_type:"save"},function(e){if(e.success==true){PMA_ajaxShowMessage(e.message);b.removeClass("inline_edit_active").addClass("inline_edit_anchor");g.each(function(){if($(this).is(":not(.relation, .enum)")){var f=$(this).find("textarea").val();if($(this).is(".transformed")){var j=getFieldName($(this),c),n=$(this);$.each(e.transformations,function(p,o){if(p==j){if($(n).is(".text_plain, .application_octetstream"))f=o;else{var q=$(n).find("textarea").val();
f=$(o).append(q)}return false}})}}else{f=$(this).find("select").val();if($(this).is(".relation")){j=getFieldName($(this),c);n=$(this);$.each(e.relations,function(p,o){if(p==j){var q=$(n).find("select").val();f=$(o).append(q);return false}})}}$(this).html(f)})}else PMA_ajaxShowMessage(e.error)})})},"top.frame_content");
function PMA_changeClassForColumn(c,a){var b=c.index();b--;c.closest("table").find("tbody tr ").has("td.data_inline_edit").each(function(){$(this).find("td.data_inline_edit:eq("+b+")").toggleClass(a)})}$(document).ready(function(){$(".column_heading").live("hover",function(){PMA_changeClassForColumn($(this),"hover")});$(".column_heading").live("click",function(){PMA_changeClassForColumn($(this),"marked")})});
