function nullify(a,c,b,d){c=document.forms.insertForm;if(typeof c.elements["funcs"+d+"["+b+"]"]!="undefined")c.elements["funcs"+d+"["+b+"]"].selectedIndex=-1;if(a==1||a==3||a==4)c.elements["field_"+b+d+"[]"].selectedIndex=-1;else if(a==2){a=c.elements["field_"+b+d+"[]"];if(a.checked)a.checked=false;else{b=a.length;for(d=0;d<b;d++)a[d].checked=false}}else if(a==6)c.elements["field_"+b+d+"[]"].value="";else c.elements["fields"+d+"["+b+"]"].value="";return true}
function daysInFebruary(a){return a%4==0&&(a%100!=0||a%400==0)?29:28}function fractionReplace(a){a=parseInt(a);var c="00";switch(a){case 1:c="01";break;case 2:c="02";break;case 3:c="03";break;case 4:c="04";break;case 5:c="05";break;case 6:c="06";break;case 7:c="07";break;case 8:c="08";break;case 9:c="09"}return c}
function isDate(a,c){a=a.replace(/[.|*|^|+|//|@]/g,"-");for(var b=a.split("-"),d=0;d<b.length;d++)if(b[d].length==1)b[d]=fractionReplace(b[d]);a=b.join("-");b=2;dtexp=RegExp(/^([0-9]{4})-(((01|03|05|07|08|10|12)-((0[0-9])|([1-2][0-9])|(3[0-1])))|((02|04|06|09|11)-((0[0-9])|([1-2][0-9])|30)))$/);if(a.length==8){dtexp=RegExp(/^([0-9]{2})-(((01|03|05|07|08|10|12)-((0[0-9])|([1-2][0-9])|(3[0-1])))|((02|04|06|09|11)-((0[0-9])|([1-2][0-9])|30)))$/);b=0}if(dtexp.test(a)){d=parseInt(a.substring(b+3,b+5));
var e=parseInt(a.substring(b+6,b+8)),f=parseInt(a.substring(0,b+2));if(d==2&&e>daysInFebruary(f))return false;if(a.substring(0,b+2).length==2)f=a.substring(0,b+2).length==2?parseInt("20"+a.substring(0,b+2)):parseInt("19"+a.substring(0,b+2));if(c==true){if(f<1978)return false;if(f>2038||f>2037&&e>19&&d>=1||f>2037&&d>1)return false}}else return false;return true}
function isTime(a){a=a.split(":");for(var c=0;c<a.length;c++)if(a[c].length==1)a[c]=fractionReplace(a[c]);a=a.join(":");tmexp=RegExp(/^(([0-1][0-9])|(2[0-3])):((0[0-9])|([1-5][0-9])):((0[0-9])|([1-5][0-9]))$/);if(!tmexp.test(a))return false;return true}
function Validator(a,c,b){var d=document.forms.insertForm,e=window.event||arguments.callee.caller.arguments[0];e=e.target||e.srcElement;unNullify(a,c);if(e.name.substring(0,6)=="fields"){d=d.elements["fields[multi_edit]["+c+"]["+a+"]"];if(b=="datetime"||b=="time"||b=="date"||b=="timestamp")if(b=="date"){if(!isDate(d.value)){d.className="invalid_value";return false}}else if(b=="time"){if(!isTime(d.value)){d.className="invalid_value";return false}}else if(b=="datetime"||b=="timestamp"){tmstmp=false;
if(d.value=="CURRENT_TIMESTAMP"){d.className="";return true}if(b=="timestamp")tmstmp=true;if(d.value=="0000-00-00 00:00:00")return true;e=d.value.indexOf(" ");if(e==-1){d.className="invalid_value";return false}else if(!(isDate(d.value.substring(0,e),tmstmp)&&isTime(d.value.substring(e+1)))){d.className="invalid_value";return false}}if(b.substring(0,3)=="int")if(isNaN(d.value)){d.className="invalid_value";return false}}}
function unNullify(a,c){var b=document.forms.insertForm;if(typeof b.elements["fields_null[multi_edit]["+c+"]["+a+"]"]!="undefined")b.elements["fields_null[multi_edit]["+c+"]["+a+"]"].checked=false;if(typeof b.elements["insert_ignore_"+c]!="undefined")b.elements["insert_ignore_"+c].checked=false;return true}
$(document).ready(function(){$(".checkbox_null").bind("click",function(){nullify($(this).siblings(".nullify_code").val(),$(this).closest("tr").find("input:hidden").first().val(),$(this).siblings(".hashed_field").val(),$(this).siblings(".multi_edit").val())});$("#insertForm").live("submit",function(a){var c=$(this);a.preventDefault();PMA_ajaxShowMessage();c.find("input:hidden").is("#ajax_request_hidden")||c.append('<input type="hidden" id="ajax_request_hidden" name="ajax_request" value="true" />');
$.post(c.attr("action"),c.serialize(),function(b){if(typeof b.success!="undefined")if(b.success==true){PMA_ajaxShowMessage(b.message);$("#topmenucontainer").next("div").remove().end().after(b.sql_query);b=$("#topmenucontainer").next("div").find(".notice");b.text()==""&&b.remove();b=c.find("select[name='submit_type']").val();if("insert"==b||"insertignore"==b)c.find("input:reset").trigger("click")}else PMA_ajaxShowMessage(PMA_messages.strErrorProcessingRequest+" : "+b.error,"7000");else{$("#insertForm").remove();
$("#topmenucontainer").after('<div id="sqlqueryresults"></div>');$("#sqlqueryresults").html(b)}})});$("#insert_rows").live("change",function(a){a.preventDefault();a=$(".insertRowTable").length;var c=$("#insert_rows").val();if(a<c){for(;a<c;){var b=$("#insertForm").find(".insertRowTable:last");$(b).clone().insertBefore("#insertForm > fieldset").find("input[name*=multi_edit],select[name*=multi_edit]").each(function(){var g=$(this).attr("name"),h=g.split(/\[\d+\]/);g=g.match(/\[\d+\]/)[0];var i=parseInt(g.match(/\d+/)[0])+
1;g=h[0]+"["+i+"]"+h[1];var j=h[1].match(/\[(.+)\]/)[1];$(this).attr("name",g);$(this).filter(".textfield").attr("value","").unbind("change").attr("onchange",null).bind("change",function(){Validator(j,i,$(this).closest("tr").find("span.column_type").html())}).end();$(this).filter(".checkbox_null").bind("click",function(){nullify($(this).siblings(".nullify_code").val(),$(this).closest("tr").find("input:hidden").first().val(),j,"[multi_edit]["+i+"]")}).end()});if(a==1)$('<input id="insert_ignore_1" type="checkbox" name="insert_ignore_1" checked="checked" />').insertBefore(".insertRowTable:last").after('<label for="insert_ignore_1">'+
PMA_messages.strIgnore+"</label>");else{b=$("#insertForm").children("input:checkbox:last");var d=$(b).attr("name"),e=parseInt(d.match(/\d+/));d=d.replace(/\d+/,e+1);$(b).clone().attr({id:d,name:d,checked:true}).add("label[for^=insert_ignore]:last").clone().attr("for",d).before("<br />").insertBefore(".insertRowTable:last")}a++}var f=0;$(".textfield").each(function(){f++;$(this).attr("tabindex",f)});$(".control_at_footer").each(function(){f++;$(this).attr("tabindex",f)})}else if(a>c)for(;a>c;){$("input[id^=insert_ignore]:last").nextUntil("fieldset").andSelf().remove();
a--}})},"top.frame_content");
