/*
 *数据安装
 */
 

Ext.onReady(function(){
Ext.QuickTips.init();
var win=new Ext.Window({
title:"数据库名称",
width:350,
height:230,
modal:true,
 
draggable:false,
layout:"fit",
items:[{
xtype:"form",
labelWidth:80,
id:"dbform",
bodyStyle:'padding:5px 5px 0 5px',
buttonAlign:"center",
items:[{
xtype:"textfield",
labelStyle:"font-weight:bolder;",
fieldLabel:"用户名",
name:"user",
msgTarget:"side",
width:200,
emptyText:"root"
},{
xtype:"textfield",
labelStyle:"font-weight:bolder;",
fieldLabel:"密码",
inputType:"password",
name:"pwd",
msgTarget:"side",
width:200,
emptyText:""
},{
xtype:"textfield",
labelStyle:"font-weight:bolder;",
fieldLabel:"数据库地址",
name:"dbaddress",
msgTarget:"side",
width:200,
emptyText:"localhost"
},{
xtype:"textfield",
labelStyle:"font-weight:bolder;",
fieldLabel:"数据库名称",
name:"dbname",
msgTarget:"side",
width:200,
allowBlank:false
},{
xtype:"radio",
name:"usenew",
inputValue:1,
checked:true,
boxLabel:"新建数据库"
},{
xtype:"radio",
name:"usenew",
inputValue:0,
boxLabel:"使用已有数据库"
},{
xtype:"button",
text:"确定",
width:50,
style:{marginLeft:"230px"},
handler:function(){
Ext.getCmp("dbform").getForm().submit({
url:"./init.php",
method:"POST",
success:function(form,action){
alert(action.result.msg);
},
failure:function(form,action){
alert(action.result.msg);
}
});
}
}]
}]
});
win.show();
});